# Generated by Django 3.2.12 on 2022-10-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_pwd',
            new_name='userpwd',
        ),
    ]
