# Generated by Django 3.2.12 on 2022-10-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('point', models.IntegerField()),
                ('detail', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('accumulated_point', models.IntegerField()),
                ('used_point', models.IntegerField()),
                ('tumbler', models.IntegerField()),
                ('bag', models.IntegerField()),
                ('container', models.IntegerField()),
            ],
        ),
    ]
